### ISSUE TITLE
Error on uninstall 

### ISSUE THREAD

**Issue by nymble** [black-lager/client#29]
had to sudo to install on uninstall no sudo got:
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/opt/homebrew/lib/python3.10/site-packages/BlackLager-1.0.1.dist-info/' -> '/opt/homebrew/lib/python3.10/site-packages/~lackLager-1.0.1.dist-info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/commands/uninstall.py", line 98, in run
    uninstall_pathset = req.uninstall(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 660, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 373, in remove
    moved.stash(path)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 271, in stash
    renames(path, new_path)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 311, in renames
    shutil.move(old, new)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 828, in move
    raise PermissionError("Cannot move the non-empty directory "
PermissionError: Cannot move the non-empty directory '/opt/homebrew/lib/python3.10/site-packages/BlackLager-1.0.1.dist-info/': Lacking write permission to '/opt/homebrew/lib/python3.10/site-packages/BlackLager-1.0.1.dist-info/'.

**Comment by nymble** [comment]
not a big issue ... ok to ignore
